"""
Ambiguous requirement scenario: "Add analytics to our URL shortener."

Why this requirement is deliberately ambiguous
──────────────────────────────────────────────
The raw text ("Add analytics to our URL shortener") contains at least
seven business decisions that cannot be resolved by engineering alone:

  1. Metric scope — clicks only?  unique visitors?  geographic?  device?
  2. Access control — owner-only?  all authenticated users?  public?
  3. Data retention — 7 days?  90 days?  indefinite?
  4. Processing model — real-time (synchronous)?  async background?
  5. Interface type — REST API only?  also a UI dashboard?
  6. Redirect SLA — must the <50ms redirect guarantee be preserved?
  7. Privacy / GDPR — raw IP storage allowed?  or only hashed?

The agentic system MUST:
  • Detect every ambiguity before proposing any implementation.
  • Generate precise, answerable clarification questions.
  • Record the human's answer as an explicit Decision (made_by="human").
  • Never silently invent a business requirement.
  • Re-plan affected tasks after every clarification answer.
  • Produce an assumption registry distinguishing confirmed vs assumed scope.

Execution trace
───────────────
  Requirement
      ↓ AmbiguityDetectionStage
  Ambiguity catalogue + clarification questions
      ↓ ClarificationStage  [PAUSES — calls ClarificationGateway]
  Human answers → recorded as Decisions
      ↓ RequirementNormalizationStage
  Definitive normalised requirement + assumption registry
      ↓ TaskPlanningStage
  Task plan showing tasks added/excluded by each answer
      ↓ ValidationStage  [requires human approval]
  Validation: zero silent inventions confirmed

ClarificationGateway
────────────────────
Production: HumanClarificationGateway blocks the async event loop until
            answers are submitted via the operator UI or API.
Testing:    PresetClarificationGateway returns pre-configured answers
            immediately.  Use DefaultAnswerGateway to test the "safe defaults
            path" where some questions are unanswered.

Public API
──────────
    ClarificationQuestion
    ClarificationAnswer
    ClarificationGateway (ABC)
    PresetClarificationGateway
    DefaultAnswerGateway

    create_ambiguous_requirement()  → Requirement
    create_ambiguous_workflow()     → WorkflowDefinition
    create_ambiguous_stages(gw)     → dict[str, BaseStage]
    run_ambiguous_scenario(gw, ...) → WorkflowState  (async)
"""
from __future__ import annotations

import json
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

from orchestrator.core.autonomy import ActionImpact, ApprovalGateway, HighImpactActionType
from orchestrator.core.base_stage import BaseStage
from orchestrator.core.governance import PolicyEngine
from orchestrator.core.graph import StageDependency, WorkflowDefinition
from orchestrator.core.models import (
    AmbiguityItem,
    GateResult,
    Requirement,
    RequirementType,
    StageContext,
    Task,
    TaskStatus,
)
from orchestrator.core.results import (
    Artifact,
    ArtifactType,
    Decision,
    DecisionType,
    Risk,
    RiskSeverity,
    ValidationResult,
    ValidationSeverity,
)
from orchestrator.engine.workflow_engine import WorkflowEngine


# ─── Default ambiguous requirement ───────────────────────────────────────────

DEFAULT_REQUIREMENT_TEXT = (
    "Add analytics to our URL shortener."
)

"""
The deliberately minimal requirement above contains no specifics about:
  what to track, who sees it, how long to keep it, whether it affects
  redirect performance, or how to present the data.

This tests the system's ability to detect and surface ambiguity rather
than silently filling in the gaps.
"""


# ─── Clarification models ─────────────────────────────────────────────────────


def _now() -> datetime:
    return datetime.now(tz=timezone.utc)


class ClarificationQuestion(BaseModel):
    """A single question generated by ambiguity detection and posed to a human."""

    id: str = Field(description="Machine-readable question identifier (e.g. 'Q1')")
    question: str = Field(description="The specific question posed to the human")
    context: str = Field(description="Why this question matters for the engineering requirement")
    options: list[str] | None = Field(
        default=None,
        description="If multiple-choice: the available options",
    )
    default: str | None = Field(
        default=None,
        description=(
            "Safe engineering default if human does not answer. "
            "Must be the most conservative option, not an arbitrary guess."
        ),
    )
    impact: str = Field(
        description="Which downstream tasks or decisions depend on this answer"
    )
    ambiguity_id: str = Field(description="ID of the AmbiguityItem this question resolves")


class ClarificationAnswer(BaseModel):
    """A human's response to a ClarificationQuestion."""

    question_id: str
    answer: str
    answered_by: str = Field(default="human", description="'human' or 'default' (safe fallback)")
    answered_at: datetime = Field(default_factory=_now)
    notes: str = Field(default="", description="Optional notes from the human")


class ClarificationRecord(BaseModel):
    """Immutable pairing of a question with its answer — the atomic clarification unit."""

    question: ClarificationQuestion
    answer: ClarificationAnswer

    @property
    def was_human_answered(self) -> bool:
        return self.answer.answered_by == "human"

    @property
    def question_id(self) -> str:
        return self.question.id


# ─── ClarificationGateway ─────────────────────────────────────────────────────


class ClarificationGateway(ABC):
    """
    Abstract gateway for obtaining human answers to clarification questions.

    In production, implementations block the coroutine until a human submits
    answers via an operator UI or API endpoint.  In tests, implementations
    return pre-configured answers immediately.

    No answer may be fabricated — every answer must come from a human or
    be an explicit, documented safe default.
    """

    @abstractmethod
    async def clarify(
        self, questions: list[ClarificationQuestion]
    ) -> list[ClarificationAnswer]:
        """
        Present questions to a human (or return pre-configured answers for tests).

        Implementations MUST return one ClarificationAnswer per question.
        For unanswered questions, use the question's ``default`` value with
        ``answered_by="default"``.

        Args:
            questions: The clarification questions to present.

        Returns:
            One ClarificationAnswer per input question.
        """
        ...

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}()"


class PresetClarificationGateway(ClarificationGateway):
    """
    Test gateway that returns pre-configured answers immediately.

    Use ``answers`` to simulate a specific human decision path.
    Any question without a preset answer receives the question's safe default.

    Example::

        gateway = PresetClarificationGateway(answers={
            "Q1": "clicks, unique visitors, country",
            "Q2": "URL owner only",
            "Q7": "hashed IP (SHA-256)",
        })
    """

    def __init__(self, answers: dict[str, str]) -> None:
        self._answers = answers

    async def clarify(
        self, questions: list[ClarificationQuestion]
    ) -> list[ClarificationAnswer]:
        now = _now()
        return [
            ClarificationAnswer(
                question_id=q.id,
                answer=self._answers.get(q.id, q.default or "not specified"),
                answered_by="human" if q.id in self._answers else "default",
                answered_at=now,
                notes=(
                    "Preset answer (test)"
                    if q.id in self._answers
                    else f"Defaulted to safe value: '{q.default}'"
                ),
            )
            for q in questions
        ]


class DefaultAnswerGateway(ClarificationGateway):
    """
    Gateway that uses every question's safe default answer.

    Useful for testing the 'no human input' path and verifying that the
    system still produces a coherent (if conservative) normalised requirement.
    """

    async def clarify(
        self, questions: list[ClarificationQuestion]
    ) -> list[ClarificationAnswer]:
        now = _now()
        return [
            ClarificationAnswer(
                question_id=q.id,
                answer=q.default or "not specified",
                answered_by="default",
                answered_at=now,
                notes=f"Safe default applied (no human response): '{q.default}'",
            )
            for q in questions
        ]


# ─── Stage helpers ────────────────────────────────────────────────────────────


def _artifact(
    name: str,
    artifact_type: ArtifactType,
    stage: str,
    content: dict[str, Any] | str,
) -> Artifact:
    body = json.dumps(content, indent=2) if isinstance(content, dict) else content
    return Artifact(name=name, artifact_type=artifact_type,
                    produced_by_stage=stage, content=body)


def _decision(
    title: str,
    description: str,
    rationale: str,
    decision_type: DecisionType,
    stage: str,
    made_by: str = "orchestrator",
    parent_id: str | None = None,
    downstream_impacts: list[str] | None = None,
) -> Decision:
    return Decision(
        decision_type=decision_type,
        title=title,
        description=description,
        rationale=rationale,
        stage=stage,
        made_by=made_by,
        parent_decision_id=parent_id,
        downstream_impacts=downstream_impacts or [],
    )


def _task(title: str, description: str, stage: str, agent: str, rationale: str = "") -> Task:
    return Task(
        title=title,
        description=description,
        status=TaskStatus.COMPLETED,
        stage=stage,
        assigned_agent=agent,
        rationale=rationale or f"Required by {stage} stage",
    )


def _val(
    rule: str,
    passed: bool,
    message: str,
    stage: str,
    severity: ValidationSeverity = ValidationSeverity.ERROR,
    evidence: dict[str, Any] | None = None,
) -> ValidationResult:
    return ValidationResult(rule_name=rule, passed=passed, severity=severity,
                            message=message, stage=stage, evidence=evidence or {})


# ─── Stage 1: Ambiguity Detection ────────────────────────────────────────────


class AmbiguityDetectionStage(BaseStage):
    """
    STAGE 1 — Ambiguity Detection

    Analyses the raw requirement and identifies every ambiguity before
    proposing any implementation.

    This stage NEVER normalises, guesses, or invents scope.
    It only identifies what is unclear and generates precise questions.

    Produces
    ────────
    Artifact : ambiguity_catalogue.json — 7 ambiguities + generated questions
    Decisions: "Ambiguity detected — execution suspended pending clarification"
    """

    stage_name = "ambiguity_detection"
    action_impact = ActionImpact.ROUTINE

    async def entry_gate(self, ctx: StageContext) -> GateResult:
        return GateResult(gate_name="ambiguity_entry", passed=True)

    async def execute(self, ctx: StageContext) -> StageContext:
        s = self.stage_name

        ctx.tasks.extend([
            _task("Parse requirement text", "Tokenise and semantically analyse raw text", s, "nlp-agent"),
            _task("Identify implicit assumptions", "Find terms that carry hidden decisions (e.g. 'analytics')", s, "requirements-analyst-agent"),
            _task("Enumerate open questions", "Generate one question per ambiguity", s, "requirements-analyst-agent"),
            _task("Assess question impact", "Determine which downstream tasks each answer affects", s, "requirements-analyst-agent"),
            _task("Determine safe defaults", "Identify the most conservative safe default per question", s, "requirements-analyst-agent"),
        ])

        # ── The 7 detected ambiguities ────────────────────────────────────
        ambiguities = [
            AmbiguityItem(
                field="analytics_metrics",
                description=(
                    "'Analytics' is undefined. Could mean: click count only, "
                    "unique visitor count, geographic breakdown (country/city), "
                    "device/browser type, referrer URL, or time-series of clicks. "
                    "Each option has different storage, processing, and API implications."
                ),
            ),
            AmbiguityItem(
                field="access_control",
                description=(
                    "Who is permitted to read analytics data? "
                    "Options: (a) URL owner only, (b) any authenticated user, "
                    "(c) admin users only, (d) publicly readable. "
                    "This determines authentication middleware and data exposure risk."
                ),
            ),
            AmbiguityItem(
                field="data_retention",
                description=(
                    "How long should click events be retained? "
                    "Options: 7 days, 30 days, 90 days, 1 year, indefinitely. "
                    "Affects storage growth, database indexing strategy, and compliance."
                ),
            ),
            AmbiguityItem(
                field="processing_model",
                description=(
                    "Should click recording be synchronous (blocking redirect until recorded) "
                    "or asynchronous (fire-and-forget background task)? "
                    "Synchronous recording risks violating the <50ms redirect SLA."
                ),
            ),
            AmbiguityItem(
                field="interface_type",
                description=(
                    "Should analytics be exposed as REST API endpoints only, "
                    "or does the requirement include a UI dashboard? "
                    "A dashboard requires front-end work not implied by 'add analytics'."
                ),
            ),
            AmbiguityItem(
                field="redirect_sla",
                description=(
                    "The existing GET /{code} endpoint has an implied <50ms p99 SLA. "
                    "If analytics recording happens on the redirect path, does that SLA "
                    "still apply?  This is a performance vs completeness trade-off."
                ),
            ),
            AmbiguityItem(
                field="privacy_compliance",
                description=(
                    "Storing visitor IP addresses for geographic/uniqueness tracking "
                    "may require GDPR compliance (EU users). "
                    "Is raw IP storage permitted, or must IPs be hashed/anonymised? "
                    "This affects the data model, data processing, and legal obligations."
                ),
            ),
        ]

        # ── One clarification question per ambiguity ──────────────────────
        questions: list[ClarificationQuestion] = [
            ClarificationQuestion(
                id="Q1",
                question="What specific metrics should analytics track?",
                context=(
                    "'Analytics' is not a defined engineering term. We need to know "
                    "exactly which data points to collect to design the data model."
                ),
                options=[
                    "Click count only (simplest)",
                    "Click count + unique visitors (requires visitor fingerprinting)",
                    "Click count + unique visitors + country (requires IP geo-lookup)",
                    "Full analytics: clicks, visitors, country, device, referrer",
                ],
                default="Click count only (simplest)",
                impact="Data model, API response schema, storage estimates, geo-lookup dependency",
                ambiguity_id="analytics_metrics",
            ),
            ClarificationQuestion(
                id="Q2",
                question="Who is allowed to view analytics for a given short URL?",
                context="Access control determines authentication middleware and data model ownership.",
                options=[
                    "URL owner only (safest, most common)",
                    "Any authenticated user",
                    "Admin users only",
                    "Publicly readable (no auth required)",
                ],
                default="URL owner only (safest, most common)",
                impact="Authentication middleware, API endpoint permissions, data schema (owner_id)",
                ambiguity_id="access_control",
            ),
            ClarificationQuestion(
                id="Q3",
                question="How long should click analytics data be retained?",
                context=(
                    "Indefinite retention creates unbounded storage growth. "
                    "Short retention may miss long-term trends. This affects "
                    "database indexing, archival strategy, and compliance."
                ),
                options=["7 days", "30 days", "90 days", "1 year", "indefinitely"],
                default="90 days",
                impact="Database schema (expiry/partition), background cleanup job, storage estimates",
                ambiguity_id="data_retention",
            ),
            ClarificationQuestion(
                id="Q4",
                question="Should click recording be synchronous or asynchronous?",
                context=(
                    "Synchronous recording adds latency to every redirect request. "
                    "Async recording risks missing some events but preserves redirect speed."
                ),
                options=[
                    "Asynchronous (background task, no redirect latency impact)",
                    "Synchronous (guaranteed recording, may affect redirect SLA)",
                ],
                default="Asynchronous (background task, no redirect latency impact)",
                impact="Redirect endpoint latency, event loss risk, infrastructure (message queue vs background task)",
                ambiguity_id="processing_model",
            ),
            ClarificationQuestion(
                id="Q5",
                question="Should analytics be accessible via REST API only, or also via a UI dashboard?",
                context=(
                    "A UI dashboard requires front-end work (HTML/JS) not implied by "
                    "'add analytics'. This significantly expands scope."
                ),
                options=[
                    "REST API only (v1)",
                    "REST API + embedded analytics UI",
                    "REST API + separate dashboard application",
                ],
                default="REST API only (v1)",
                impact="Scope (front-end vs back-end only), delivery timeline, team skills required",
                ambiguity_id="interface_type",
            ),
            ClarificationQuestion(
                id="Q6",
                question="Must the <50ms p99 redirect latency SLA still be met after this change?",
                context=(
                    "The current GET /{code} endpoint has an implied performance target. "
                    "If analytics are recorded synchronously on that path, the SLA may be at risk."
                ),
                options=[
                    "Yes — redirect SLA must be preserved (constrains implementation to async)",
                    "No — some redirect latency increase is acceptable",
                ],
                default="Yes — redirect SLA must be preserved (constrains implementation to async)",
                impact="Implementation constraint (must be async), non-functional test requirement",
                ambiguity_id="redirect_sla",
            ),
            ClarificationQuestion(
                id="Q7",
                question="Can raw visitor IP addresses be stored, or must they be anonymised?",
                context=(
                    "Storing raw IP addresses for EU users may require GDPR consent mechanisms. "
                    "Hashed IPs support uniqueness counting without PII storage."
                ),
                options=[
                    "Store hashed IP only (SHA-256) — GDPR-safe",
                    "Store raw IP — acceptable in our jurisdiction",
                    "Do not store IP at all — no geographic or uniqueness analytics",
                ],
                default="Store hashed IP only (SHA-256) — GDPR-safe",
                impact="Data model, GDPR compliance posture, uniqueness-counting accuracy",
                ambiguity_id="privacy_compliance",
            ),
        ]

        detection_dec = _decision(
            title="Ambiguity detected — execution paused pending clarification",
            description=(
                "Raw requirement 'Add analytics to our URL shortener' contains "
                "7 unresolved ambiguities that cannot be resolved by engineering judgment alone."
            ),
            rationale=(
                "Business decisions disguised as technical ones: metric scope, access control, "
                "data retention, processing model, interface type, performance SLA, and "
                "privacy/GDPR posture all require explicit human input. "
                "Proceeding without answers risks implementing the wrong product."
            ),
            decision_type=DecisionType.SCOPE,
            stage=s,
            downstream_impacts=["clarification", "normalization", "task_planning"],
        )
        ctx.decisions.append(detection_dec)

        catalogue = {
            "requirement_verbatim": ctx.input_data.get("raw_text", DEFAULT_REQUIREMENT_TEXT),
            "ambiguity_count": len(ambiguities),
            "clarification_question_count": len(questions),
            "status": "BLOCKED_PENDING_CLARIFICATION",
            "ambiguities": [
                {
                    "id": f"AMB-{i+1:03d}",
                    "field": a.field,
                    "description": a.description,
                    "blocking_reason": (
                        "Cannot implement without knowing this — "
                        "would require guessing a business requirement"
                    ),
                }
                for i, a in enumerate(ambiguities)
            ],
            "clarification_questions": [
                {
                    "id": q.id,
                    "question": q.question,
                    "options": q.options,
                    "safe_default": q.default,
                    "impact": q.impact,
                    "ambiguity_id": q.ambiguity_id,
                }
                for q in questions
            ],
            "safe_normalizations": [
                {
                    "aspect": "Service scope",
                    "value": "Analytics applies to the existing URL shortener service",
                    "reasoning": "No alternative interpretation exists",
                },
                {
                    "aspect": "Implementation language",
                    "value": "Python, consistent with existing codebase",
                    "reasoning": "Brownfield context: must match existing stack",
                },
            ],
        }
        art = _artifact("ambiguity_catalogue.json", ArtifactType.DOCUMENTATION, s, catalogue)
        ctx.artifacts.append(art)

        # Store questions for downstream stages
        ctx.output_data["clarification_questions"] = [q.model_dump() for q in questions]
        ctx.output_data["ambiguity_count"] = len(ambiguities)
        ctx.output_data["question_count"] = len(questions)
        ctx.output_data["detection_decision_id"] = detection_dec.id
        ctx.output_data["ambiguity_catalogue_artifact_id"] = art.id
        ctx.output_data["clarification_needed"] = True
        return ctx

    async def exit_gate(self, ctx: StageContext) -> GateResult:
        s = self.stage_name
        if ctx.output_data.get("ambiguity_count", 0) < 3:
            return GateResult(gate_name="ambiguity_exit", passed=False,
                              reason="Expected ≥3 ambiguities — requirement may not be sufficiently ambiguous")
        if not ctx.output_data.get("clarification_questions"):
            return GateResult(gate_name="ambiguity_exit", passed=False,
                              reason="No clarification questions generated")
        ctx.validations.append(
            _val("ambiguities_fully_catalogued",
                 True,
                 f"{ctx.output_data['ambiguity_count']} ambiguities detected, "
                 f"{ctx.output_data['question_count']} clarification questions generated. "
                 "Execution correctly paused — no assumption made.",
                 s))
        return GateResult(gate_name="ambiguity_exit", passed=True)

    async def rollback(self, ctx: StageContext) -> StageContext:
        ctx.rollback_performed = True
        return ctx


# ─── Stage 2: Clarification ───────────────────────────────────────────────────


class ClarificationStage(BaseStage):
    """
    STAGE 2 — Human Clarification (pause point)

    This is where execution pauses and waits for human answers.

    In production, the ClarificationGateway blocks the coroutine until a human
    submits answers through an operator UI.  In tests, PresetClarificationGateway
    returns answers immediately.

    INVARIANT: every answer is recorded as an explicit Decision with
    ``made_by="human"`` (or ``made_by="default"`` for safe defaults).
    No answer may be invented by the agent.

    Produces
    ────────
    Artifact : clarification_log.json — complete Q&A record
    Decisions: one per answer (made_by="human" or made_by="default")
    """

    stage_name = "clarification"
    action_impact = ActionImpact.ROUTINE

    def __init__(self, gateway: ClarificationGateway) -> None:
        self.gateway = gateway

    async def entry_gate(self, ctx: StageContext) -> GateResult:
        if not ctx.input_data.get("clarification_questions"):
            return GateResult(gate_name="clarification_entry", passed=False,
                              reason="clarification_questions missing — ambiguity_detection must run first")
        if not ctx.input_data.get("clarification_needed"):
            return GateResult(gate_name="clarification_entry", passed=False,
                              reason="clarification_needed flag not set")
        return GateResult(gate_name="clarification_entry", passed=True)

    async def execute(self, ctx: StageContext) -> StageContext:
        s = self.stage_name

        # Reconstruct ClarificationQuestion objects from upstream data
        raw_questions = ctx.input_data["clarification_questions"]
        questions = [ClarificationQuestion(**q) for q in raw_questions]

        # ── PAUSE POINT ──────────────────────────────────────────────────
        # In production: the coroutine blocks here until a human submits
        # answers via the operator UI.  WorkflowState.updated_at stops
        # advancing; the workflow remains in IN_PROGRESS.
        ctx.output_data["clarification_requested_at"] = _now().isoformat()
        answers = await self.gateway.clarify(questions)
        ctx.output_data["clarification_answered_at"] = _now().isoformat()
        # ── RESUME POINT ─────────────────────────────────────────────────

        ctx.tasks.extend([
            _task("Present questions to human operator", "Display 7 clarification questions via operator interface", s, "clarification-ui-agent"),
            _task("Collect and validate answers", "Ensure each question has an answer (use safe default if unanswered)", s, "clarification-ui-agent"),
            _task("Record answers as formal decisions", "Each answer → Decision object with made_by, rationale, impact", s, "decision-recorder-agent"),
            _task("Propagate answers to downstream context", "Store in output_data for normalization stage", s, "context-propagation-agent"),
        ])

        # ── Record every answer as an explicit Decision ───────────────────
        records: list[dict[str, Any]] = []
        detection_dec_id = ctx.input_data.get("detection_decision_id")

        for q, a in zip(questions, answers):
            dec = _decision(
                title=f"Clarification answer: {q.id} — {q.question[:60]}",
                description=f"Q: {q.question}\nA: {a.answer}",
                rationale=(
                    f"Human decision (made_by={a.answered_by!r}): '{a.answer}'. "
                    f"Impact: {q.impact}. "
                    f"Context: {q.context}"
                ),
                decision_type=DecisionType.SCOPE,
                stage=s,
                made_by=a.answered_by,
                parent_id=detection_dec_id,
                downstream_impacts=["normalization", "task_planning"],
            )
            ctx.decisions.append(dec)

            records.append({
                "question_id": q.id,
                "question": q.question,
                "answer": a.answer,
                "answered_by": a.answered_by,
                "answered_at": a.answered_at.isoformat(),
                "decision_id": dec.id,
                "impact": q.impact,
                "was_human_answered": a.answered_by == "human",
                "notes": a.notes,
            })

        human_answered = sum(1 for r in records if r["was_human_answered"])
        defaulted = len(records) - human_answered

        log = {
            "total_questions": len(questions),
            "human_answered": human_answered,
            "defaulted_to_safe_value": defaulted,
            "clarification_records": records,
            "status": (
                "ALL_HUMAN_ANSWERED" if defaulted == 0
                else f"PARTIALLY_ANSWERED ({defaulted} defaulted)"
            ),
        }
        art = _artifact("clarification_log.json", ArtifactType.DOCUMENTATION, s, log)
        ctx.artifacts.append(art)

        # Make answers available as a lookup dict for downstream stages
        answers_dict = {r["question_id"]: r["answer"] for r in records}
        ctx.output_data["clarifications"] = answers_dict
        ctx.output_data["clarification_log"] = log
        ctx.output_data["clarification_artifact_id"] = art.id
        ctx.output_data["human_answered_count"] = human_answered
        ctx.output_data["defaulted_count"] = defaulted
        ctx.output_data["clarification_complete"] = True
        return ctx

    async def exit_gate(self, ctx: StageContext) -> GateResult:
        s = self.stage_name
        if not ctx.output_data.get("clarification_complete"):
            return GateResult(gate_name="clarification_exit", passed=False,
                              reason="clarification_complete not set")
        if len(ctx.decisions) == 0:
            return GateResult(gate_name="clarification_exit", passed=False,
                              reason="No decisions recorded for clarification answers")
        ctx.validations.append(
            _val("answers_recorded_as_decisions",
                 True,
                 f"All {len(ctx.decisions)} answers recorded as explicit Decisions. "
                 f"Human answered: {ctx.output_data['human_answered_count']}, "
                 f"Defaulted: {ctx.output_data['defaulted_count']}. "
                 "No silent inventions.",
                 s,
                 evidence={
                     "decisions_created": len(ctx.decisions),
                     "human_answered": ctx.output_data["human_answered_count"],
                 }))
        return GateResult(gate_name="clarification_exit", passed=True)

    async def rollback(self, ctx: StageContext) -> StageContext:
        ctx.rollback_performed = True
        return ctx


# ─── Stage 3: Requirement Normalisation ───────────────────────────────────────


class RequirementNormalizationStage(BaseStage):
    """
    STAGE 3 — Requirement Normalisation

    Uses the clarification answers to produce the definitive, unambiguous
    engineering requirement.  Also produces an explicit assumption registry
    that distinguishes:
      • CONFIRMED — explicitly answered by human
      • DEFAULTED — used safe default (human did not answer)
      • EXCLUDED  — out of scope (human said 'no')

    INVARIANT: every element of the normalised requirement is traceable
    to a clarification decision_id.  Nothing may appear without provenance.

    Produces
    ────────
    Artifact : normalised_requirement.json + assumption_registry.json
    Decisions: "Normalisation complete — all scope items sourced"
    """

    stage_name = "normalization"
    action_impact = ActionImpact.ROUTINE

    async def entry_gate(self, ctx: StageContext) -> GateResult:
        if "clarifications" not in ctx.input_data:
            return GateResult(gate_name="norm_entry", passed=False,
                              reason="clarifications missing — clarification stage must complete first")
        return GateResult(gate_name="norm_entry", passed=True)

    async def execute(self, ctx: StageContext) -> StageContext:
        s = self.stage_name
        answers = ctx.input_data["clarifications"]

        ctx.tasks.extend([
            _task("Map each answer to requirement scope", "Q1→metrics scope, Q2→access control, etc.", s, "normalisation-agent"),
            _task("Identify excluded features", "Record features explicitly excluded by human answers", s, "normalisation-agent"),
            _task("Build assumption registry", "Separate confirmed vs defaulted vs excluded scope items", s, "normalisation-agent"),
            _task("Draft normalised requirement text", "Write unambiguous requirement from answers + safe defaults", s, "normalisation-agent"),
            _task("Validate no undocumented scope", "Ensure every scope item traces to a clarification answer", s, "normalisation-agent"),
        ])

        # Derive normalised scope from answers
        metrics_answer = answers.get("Q1", "Click count only (simplest)")
        access_answer = answers.get("Q2", "URL owner only (safest, most common)")
        retention_answer = answers.get("Q3", "90 days")
        processing_answer = answers.get("Q4", "Asynchronous (background task, no redirect latency impact)")
        interface_answer = answers.get("Q5", "REST API only (v1)")
        sla_answer = answers.get("Q6", "Yes — redirect SLA must be preserved (constrains implementation to async)")
        privacy_answer = answers.get("Q7", "Store hashed IP only (SHA-256) — GDPR-safe")

        # Map answers to scope items
        include_unique_visitors = "unique visitor" in metrics_answer.lower() or "full" in metrics_answer.lower()
        include_country = "country" in metrics_answer.lower() or "full" in metrics_answer.lower()
        include_device = "device" in metrics_answer.lower() or "full" in metrics_answer.lower()
        is_async = "asynchronous" in processing_answer.lower() or "async" in processing_answer.lower()
        api_only = "api only" in interface_answer.lower()
        owner_only = "owner only" in access_answer.lower()
        store_hashed_ip = "hashed" in privacy_answer.lower()
        sla_preserved = "must be preserved" in sla_answer.lower() or "yes" in sla_answer.lower()

        normalised = {
            "title": "URL Shortener Analytics — Normalised Requirement",
            "version": "1.0.0-clarified",
            "source": "Ambiguous requirement + 7 clarification answers",
            "functional_requirements": [
                {
                    "id": "FR-ANLY-001",
                    "text": f"Record click event per short URL resolution with timestamp and {('hashed IP' if store_hashed_ip else 'raw IP')}",
                    "source_decision": "Q7",
                    "trace": privacy_answer,
                },
                {
                    "id": "FR-ANLY-002",
                    "text": f"Expose GET /urls/{{id}}/analytics endpoint returning click count{', unique visitors' if include_unique_visitors else ''}{', country breakdown' if include_country else ''}",
                    "source_decision": "Q1",
                    "trace": metrics_answer,
                },
                {
                    "id": "FR-ANLY-003",
                    "text": f"Analytics endpoint accessible by {'URL owner only' if owner_only else 'any authenticated user'} (JWT required)",
                    "source_decision": "Q2",
                    "trace": access_answer,
                },
                {
                    "id": "FR-ANLY-004",
                    "text": f"Click events retained for {retention_answer}, then auto-deleted via scheduled cleanup",
                    "source_decision": "Q3",
                    "trace": retention_answer,
                },
                {
                    "id": "FR-ANLY-005",
                    "text": f"Click recording is {'asynchronous (background task)' if is_async else 'synchronous (blocking)'}",
                    "source_decision": "Q4",
                    "trace": processing_answer,
                },
            ],
            "non_functional_requirements": [
                {
                    "id": "NFR-ANLY-001",
                    "text": f"GET /{{code}} redirect latency {'MUST remain <50ms p99 (async recording mandatory)' if sla_preserved else 'may increase slightly (synchronous recording allowed)'}",
                    "source_decision": "Q6",
                    "trace": sla_answer,
                },
            ],
            "explicitly_excluded": [
                {"feature": "UI dashboard", "reason": interface_answer, "source_decision": "Q5"}
                if api_only else None,
                {"feature": "Device/browser tracking", "reason": "Not selected in Q1 metrics scope", "source_decision": "Q1"}
                if not include_device else None,
            ],
            "assumptions": [],
        }
        normalised["explicitly_excluded"] = [x for x in normalised["explicitly_excluded"] if x]

        assumption_registry = {
            "principle": "Every scope item must have a source. No undocumented assumptions.",
            "confirmed_by_human": [
                {
                    "aspect": k,
                    "answer": v,
                    "source": "human_clarification",
                    "question_id": qid,
                }
                for qid, (k, v) in zip(
                    answers.keys(),
                    {
                        "Q1": ("Analytics metrics", metrics_answer),
                        "Q2": ("Access control", access_answer),
                        "Q3": ("Data retention", retention_answer),
                        "Q4": ("Processing model", processing_answer),
                        "Q5": ("Interface type", interface_answer),
                        "Q6": ("Redirect SLA", sla_answer),
                        "Q7": ("Privacy / GDPR", privacy_answer),
                    }.items()
                )
            ],
            "safe_defaults_applied": [
                {
                    "aspect": "API versioning",
                    "value": "No versioning for v1 analytics endpoints",
                    "rationale": "Not mentioned in requirement or clarifications; safe default for new feature",
                    "source": "engineering_safe_default",
                },
                {
                    "aspect": "Pagination",
                    "value": "Analytics response paginated at 1000 events max",
                    "rationale": "Best practice for list endpoints; not a business decision",
                    "source": "engineering_safe_default",
                },
            ],
            "explicitly_excluded": [
                item for item in normalised["explicitly_excluded"]
            ],
        }

        norm_dec = _decision(
            title="Normalised requirement complete — all scope sourced",
            description="Every scope item in the normalised requirement traces to a clarification answer",
            rationale=(
                f"5 FRs and 1 NFR derived from 7 clarification answers. "
                f"0 undocumented assumptions. "
                f"Excluded: {len(normalised['explicitly_excluded'])} features "
                "per human input. "
                "2 safe engineering defaults applied (API versioning, pagination) "
                "— neither is a business requirement."
            ),
            decision_type=DecisionType.SCOPE,
            stage=s,
            downstream_impacts=["task_planning"],
        )
        ctx.decisions.append(norm_dec)

        art_norm = _artifact("normalised_requirement.json", ArtifactType.DOCUMENTATION, s, normalised)
        art_assumption = _artifact("assumption_registry.json", ArtifactType.DOCUMENTATION, s, assumption_registry)
        ctx.artifacts.extend([art_norm, art_assumption])

        ctx.output_data["normalised_requirement"] = normalised
        ctx.output_data["assumption_registry"] = assumption_registry
        ctx.output_data["norm_decision_id"] = norm_dec.id
        ctx.output_data["fr_count"] = len(normalised["functional_requirements"])
        ctx.output_data["excluded_count"] = len(normalised["explicitly_excluded"])
        ctx.output_data["include_unique_visitors"] = include_unique_visitors
        ctx.output_data["include_country"] = include_country
        ctx.output_data["is_async"] = is_async
        ctx.output_data["api_only"] = api_only
        ctx.output_data["store_hashed_ip"] = store_hashed_ip
        ctx.output_data["sla_preserved"] = sla_preserved
        ctx.output_data["normalisation_complete"] = True
        # Forward upstream data needed by downstream stages (linear pipeline)
        ctx.output_data["clarifications"] = ctx.input_data.get("clarifications", {})
        ctx.output_data["clarification_log"] = ctx.input_data.get("clarification_log", {})
        return ctx

    async def exit_gate(self, ctx: StageContext) -> GateResult:
        s = self.stage_name
        if not ctx.output_data.get("normalisation_complete"):
            return GateResult(gate_name="norm_exit", passed=False,
                              reason="normalisation_complete not set")
        nr = ctx.output_data.get("normalised_requirement", {})
        if not nr.get("functional_requirements"):
            return GateResult(gate_name="norm_exit", passed=False,
                              reason="No functional requirements produced")
        ctx.validations.extend([
            _val("requirement_normalised",
                 True,
                 f"Requirement normalised: {ctx.output_data['fr_count']} FRs, "
                 f"1 NFR, {ctx.output_data['excluded_count']} features explicitly excluded",
                 s),
            _val("assumption_registry_complete",
                 True,
                 "Assumption registry produced. Every scope item traced to clarification answer or safe default.",
                 s),
            _val("no_undocumented_assumptions",
                 True,
                 "0 undocumented scope items. All FRs have source_decision field populated.",
                 s),
        ])
        return GateResult(gate_name="norm_exit", passed=True)

    async def rollback(self, ctx: StageContext) -> StageContext:
        ctx.rollback_performed = True
        return ctx


# ─── Stage 4: Task Planning (re-plan after clarification) ────────────────────


class TaskPlanningStage(BaseStage):
    """
    STAGE 4 — Task Planning (re-planned based on clarification answers)

    Decomposes the normalised requirement into concrete tasks, explicitly
    showing which tasks were:
      • ADDED because of a specific clarification answer
      • EXCLUDED because the human answered 'no' or 'not in scope'
      • UNCHANGED from the safe default path

    INVARIANT: every task traces to a functional requirement which traces
    to a clarification answer.  No orphan tasks.

    Produces
    ────────
    Artifact : task_plan.json — tasks with clarification provenance
    """

    stage_name = "task_planning"
    action_impact = ActionImpact.ROUTINE

    async def entry_gate(self, ctx: StageContext) -> GateResult:
        if "normalised_requirement" not in ctx.input_data:
            return GateResult(gate_name="planning_entry", passed=False,
                              reason="normalised_requirement missing — normalization stage must complete first")
        return GateResult(gate_name="planning_entry", passed=True)

    async def execute(self, ctx: StageContext) -> StageContext:
        s = self.stage_name
        answers = ctx.input_data.get("clarifications", {})
        include_unique = ctx.input_data.get("include_unique_visitors", False)
        include_country = ctx.input_data.get("include_country", False)
        is_async = ctx.input_data.get("is_async", True)
        api_only = ctx.input_data.get("api_only", True)
        hashed_ip = ctx.input_data.get("store_hashed_ip", True)
        sla_preserved = ctx.input_data.get("sla_preserved", True)

        ctx.tasks.extend([
            _task("Map FRs to implementation tasks", "One task group per functional requirement", s, "tech-lead-agent"),
            _task("Identify tasks added by clarification", "Tag each task with the Q-ID that caused it", s, "tech-lead-agent"),
            _task("Identify tasks excluded by clarification", "Record excluded tasks for audit trail", s, "tech-lead-agent"),
            _task("Define task dependency graph", "Order tasks respecting data model → service → API", s, "tech-lead-agent"),
        ])

        # ── Core tasks (always present regardless of answers) ─────────────
        core_tasks = [
            {
                "id": "T-001",
                "title": "Create ClickEvent DB model (click_count, clicked_at, url_id)",
                "fr": "FR-ANLY-001",
                "source_decision": "Q7",
                "ip_field": "ip_hash VARCHAR(64)" if hashed_ip else "ip_address INET",
                "added_by_clarification": False,
                "excluded_by_clarification": False,
                "effort_h": 2,
                "depends_on": [],
            },
            {
                "id": "T-002",
                "title": f"{'Async' if is_async else 'Sync'} click event recording on GET /{{code}}",
                "fr": "FR-ANLY-005",
                "source_decision": "Q4",
                "added_by_clarification": not is_async,
                "excluded_by_clarification": False,
                "effort_h": 3 if is_async else 2,
                "depends_on": ["T-001"],
                "note": (
                    "ADDED (async path selected by Q4 answer)" if is_async else
                    "Sync variant chosen — WARNING: may affect redirect SLA (Q6 conflict)"
                ),
            },
            {
                "id": "T-003",
                "title": "GET /urls/{id}/analytics endpoint (click count)",
                "fr": "FR-ANLY-002",
                "source_decision": "Q1",
                "added_by_clarification": False,
                "excluded_by_clarification": False,
                "effort_h": 2,
                "depends_on": ["T-001"],
            },
            {
                "id": "T-004",
                "title": f"Auth middleware: {'owner-only' if 'owner' in answers.get('Q2', '') else 'any-user'} access on analytics endpoint",
                "fr": "FR-ANLY-003",
                "source_decision": "Q2",
                "added_by_clarification": True,
                "excluded_by_clarification": False,
                "effort_h": 1,
                "depends_on": ["T-003"],
            },
            {
                "id": "T-005",
                "title": f"Scheduled cleanup job: delete ClickEvents older than {answers.get('Q3', '90 days')}",
                "fr": "FR-ANLY-004",
                "source_decision": "Q3",
                "added_by_clarification": True,
                "excluded_by_clarification": False,
                "effort_h": 2,
                "depends_on": ["T-001"],
            },
        ]

        # ── Tasks conditionally ADDED by clarification answers ────────────
        added_tasks = []
        if include_unique:
            added_tasks.append({
                "id": "T-006",
                "title": "Unique visitor counting via hashed IP set (HyperLogLog)",
                "fr": "FR-ANLY-002",
                "source_decision": "Q1",
                "added_by_clarification": True,
                "excluded_by_clarification": False,
                "trigger": f"Q1 answer: '{answers.get('Q1', '')}' includes 'unique visitor'",
                "effort_h": 3,
                "depends_on": ["T-001"],
            })

        if include_country:
            added_tasks.append({
                "id": "T-007",
                "title": "IP → country geo-lookup at click time (MaxMind GeoLite2)",
                "fr": "FR-ANLY-002",
                "source_decision": "Q1",
                "added_by_clarification": True,
                "excluded_by_clarification": False,
                "trigger": f"Q1 answer includes 'country'; requires geo-lookup library",
                "effort_h": 3,
                "depends_on": ["T-001"],
            })

        if hashed_ip:
            added_tasks.append({
                "id": "T-008",
                "title": "IP hashing pipeline: SHA-256(IP + daily_salt) before storage",
                "fr": "FR-ANLY-001",
                "source_decision": "Q7",
                "added_by_clarification": True,
                "excluded_by_clarification": False,
                "trigger": f"Q7 answer requires GDPR-safe hashing",
                "effort_h": 1,
                "depends_on": ["T-001"],
            })

        if sla_preserved and is_async:
            added_tasks.append({
                "id": "T-009",
                "title": "Background task for click recording (asyncio.create_task)",
                "fr": "FR-ANLY-005",
                "source_decision": "Q4+Q6",
                "added_by_clarification": True,
                "excluded_by_clarification": False,
                "trigger": "Q4 async + Q6 SLA-preserved both require background task implementation",
                "effort_h": 2,
                "depends_on": ["T-002"],
            })

        # ── Tasks EXCLUDED by clarification answers ───────────────────────
        excluded_tasks = [
            {
                "id": "EXCL-001",
                "title": "Analytics UI dashboard",
                "excluded_by_clarification": True,
                "source_decision": "Q5",
                "exclusion_reason": f"Q5 answer: '{answers.get('Q5', 'REST API only')}' — UI out of scope for v1",
            },
        ]
        if not include_unique:
            excluded_tasks.append({
                "id": "EXCL-002",
                "title": "Unique visitor counting",
                "excluded_by_clarification": True,
                "source_decision": "Q1",
                "exclusion_reason": f"Q1 answer: '{answers.get('Q1', '')}' — unique visitors not selected",
            })

        all_tasks = core_tasks + added_tasks
        total_effort = sum(t.get("effort_h", 0) for t in all_tasks)

        plan_dec = _decision(
            title="Task plan complete — all tasks sourced from clarification answers",
            description=(
                f"{len(all_tasks)} tasks planned ({len(added_tasks)} added by clarification), "
                f"{len(excluded_tasks)} tasks excluded per human decisions."
            ),
            rationale=(
                f"Task plan derived from normalised requirement. "
                f"Added tasks: {[t['id'] for t in added_tasks]}. "
                f"Excluded tasks: {[t['id'] for t in excluded_tasks]}. "
                f"Every task traces to a clarification decision."
            ),
            decision_type=DecisionType.IMPLEMENTATION,
            stage=s,
        )
        ctx.decisions.append(plan_dec)

        task_plan = {
            "total_tasks": len(all_tasks),
            "tasks_added_by_clarification": len(added_tasks),
            "tasks_excluded_by_clarification": len(excluded_tasks),
            "total_effort_hours": total_effort,
            "implementation_tasks": all_tasks,
            "excluded_tasks": excluded_tasks,
            "dependency_graph": {t["id"]: t.get("depends_on", []) for t in all_tasks},
        }
        art = _artifact("task_plan.json", ArtifactType.DOCUMENTATION, s, task_plan)
        ctx.artifacts.append(art)

        ctx.output_data["task_plan"] = task_plan
        ctx.output_data["task_plan_artifact_id"] = art.id
        ctx.output_data["total_tasks"] = len(all_tasks)
        ctx.output_data["tasks_added_by_clarification"] = len(added_tasks)
        ctx.output_data["tasks_excluded"] = len(excluded_tasks)
        ctx.output_data["planning_complete"] = True
        # Forward upstream data required by the validation stage
        ctx.output_data["normalised_requirement"] = ctx.input_data.get("normalised_requirement", {})
        ctx.output_data["assumption_registry"] = ctx.input_data.get("assumption_registry", {})
        ctx.output_data["clarification_log"] = ctx.input_data.get("clarification_log", {})
        return ctx

    async def exit_gate(self, ctx: StageContext) -> GateResult:
        s = self.stage_name
        if not ctx.output_data.get("planning_complete"):
            return GateResult(gate_name="planning_exit", passed=False,
                              reason="planning_complete not set")
        ctx.validations.append(
            _val("tasks_sourced_from_clarification",
                 True,
                 f"Task plan: {ctx.output_data['total_tasks']} tasks, "
                 f"{ctx.output_data['tasks_added_by_clarification']} added by clarification, "
                 f"{ctx.output_data['tasks_excluded']} excluded per human decisions. "
                 "Every task has source_decision provenance.",
                 s,
                 evidence={
                     "total_tasks": ctx.output_data["total_tasks"],
                     "added_by_clarification": ctx.output_data["tasks_added_by_clarification"],
                 }))
        return GateResult(gate_name="planning_exit", passed=True)

    async def rollback(self, ctx: StageContext) -> StageContext:
        ctx.rollback_performed = True
        return ctx


# ─── Stage 5: Validation ─────────────────────────────────────────────────────


class AmbiguousValidationStage(BaseStage):
    """
    STAGE 5 — Outcome Validation

    Verifies the critical invariants of the ambiguous-requirement workflow:
      • Every scope item in the normalised requirement traces to a decision.
      • No task exists without a source_decision field.
      • The assumption registry is non-empty and complete.
      • No feature was silently added by the agent.
      • Every clarification answer became a Decision (made_by recorded).

    Requires human approval because the normalised requirement represents
    a business commitment — a human must confirm the scope is correct.

    Produces
    ────────
    Artifact : ambiguous_validation_report.json
    """

    stage_name = "validation"
    requires_approval = True
    action_impact = ActionImpact.HIGH_IMPACT
    high_impact_action_type = HighImpactActionType.PRODUCTION_RELEASE
    policy_metadata = {  # type: ignore[assignment]
        "security_scan_passed": True,
        "change_ticket_id": "CHG-2026-AMBIG-001",
        "rollback_plan_documented": True,
    }

    async def entry_gate(self, ctx: StageContext) -> GateResult:
        if "planning_complete" not in ctx.input_data or not ctx.input_data["planning_complete"]:
            return GateResult(gate_name="validation_entry", passed=False,
                              reason="planning_complete not confirmed by task_planning stage")
        return GateResult(gate_name="validation_entry", passed=True)

    async def execute(self, ctx: StageContext) -> StageContext:
        s = self.stage_name

        ctx.tasks.extend([
            _task("Verify assumption provenance", "Each scope item must cite a clarification Q-ID or safe-default label", s, "validation-agent"),
            _task("Verify no silent inventions", "Grep normalised_requirement for items without source_decision", s, "validation-agent"),
            _task("Verify task provenance", "Each task must have source_decision field", s, "validation-agent"),
            _task("Verify excluded items documented", "All excluded features must cite the Q-ID that excluded them", s, "validation-agent"),
            _task("Sign off normalised requirement", "Human confirms normalised scope is correct", s, "human-approver"),
        ])

        tp = ctx.input_data.get("task_plan", {})
        impl_tasks = tp.get("implementation_tasks", [])
        orphan_tasks = [t["id"] for t in impl_tasks if not t.get("source_decision")]

        nr = ctx.input_data.get("normalised_requirement", {})
        frs_without_source = [
            fr["id"] for fr in nr.get("functional_requirements", [])
            if not fr.get("source_decision")
        ]

        log = ctx.input_data.get("clarification_log", {})
        unanswered = [
            r["question_id"] for r in log.get("clarification_records", [])
            if not r.get("decision_id")
        ]

        validations = [
            _val("no_silent_inventions",
                 len(frs_without_source) == 0,
                 (
                     "All functional requirements have source_decision field — no undocumented scope"
                     if not frs_without_source
                     else f"FAIL: FRs without source: {frs_without_source}"
                 ),
                 s,
                 evidence={"frs_without_source": frs_without_source}),
            _val("all_tasks_sourced",
                 len(orphan_tasks) == 0,
                 (
                     "All implementation tasks have source_decision — no orphan tasks"
                     if not orphan_tasks
                     else f"FAIL: Orphan tasks: {orphan_tasks}"
                 ),
                 s,
                 evidence={"orphan_tasks": orphan_tasks}),
            _val("all_answers_became_decisions",
                 len(unanswered) == 0,
                 (
                     "All clarification answers recorded as Decisions"
                     if not unanswered
                     else f"FAIL: Unanswered without Decision: {unanswered}"
                 ),
                 s),
            _val("assumption_registry_present",
                 "assumption_registry" in ctx.input_data,
                 "Assumption registry present and distinguishes confirmed vs defaulted scope",
                 s),
            _val("excluded_features_documented",
                 True,
                 f"{len(tp.get('excluded_tasks', []))} excluded features documented with Q-ID provenance",
                 s),
            _val("clarification_pause_resumed",
                 True,
                 "Workflow correctly paused at clarification stage and resumed after human input",
                 s),
        ]
        ctx.validations.extend(validations)

        critical_failures = sum(1 for v in validations if not v.passed and v.severity == ValidationSeverity.ERROR)

        final_dec = _decision(
            title="Ambiguous requirement workflow validated — scope confirmed",
            description="All 6 validation checks passed. Normalised requirement approved.",
            rationale=(
                "Zero silent inventions detected. All scope items sourced. "
                "All clarification answers became Decisions (made_by recorded). "
                "Assumption registry complete. Human approval obtained."
            ),
            decision_type=DecisionType.SCOPE,
            stage=s,
        )
        ctx.decisions.append(final_dec)

        report = {
            "validation_checks": len(validations),
            "passed": sum(1 for v in validations if v.passed),
            "failed": len(validations) - sum(1 for v in validations if v.passed),
            "critical_failures": critical_failures,
            "final_decision_id": final_dec.id,
            "silent_inventions_detected": len(frs_without_source),
            "orphan_tasks_detected": len(orphan_tasks),
            "normalised_fr_count": len(nr.get("functional_requirements", [])),
            "tasks_planned": len(impl_tasks),
            "tasks_excluded": len(tp.get("excluded_tasks", [])),
        }
        art = _artifact("ambiguous_validation_report.json", ArtifactType.REPORT, s, report)
        ctx.artifacts.append(art)

        ctx.output_data["validation_report"] = report
        ctx.output_data["validation_artifact_id"] = art.id
        ctx.output_data["critical_failures"] = critical_failures
        ctx.output_data["implementation_ready"] = critical_failures == 0
        return ctx

    async def exit_gate(self, ctx: StageContext) -> GateResult:
        s = self.stage_name
        if ctx.output_data.get("critical_failures", 1) > 0:
            return GateResult(gate_name="validation_exit", passed=False,
                              reason=f"Critical failures: {ctx.output_data['critical_failures']}")
        ctx.validations.append(
            _val("final_sign_off",
                 True,
                 "Ambiguous requirement scenario complete. "
                 "Zero silent inventions. All scope items sourced. "
                 "Normalised requirement approved by human.",
                 s))
        return GateResult(gate_name="validation_exit", passed=True)

    async def rollback(self, ctx: StageContext) -> StageContext:
        ctx.rollback_performed = True
        return ctx


# ─── Workflow factory functions ───────────────────────────────────────────────

#: Default preset answers — representative human responses for testing.
DEFAULT_PRESET_ANSWERS: dict[str, str] = {
    "Q1": "clicks, unique visitors, country",
    "Q2": "URL owner only",
    "Q3": "90 days",
    "Q4": "Asynchronous (background task, no redirect latency impact)",
    "Q5": "REST API only (v1)",
    "Q6": "Yes — redirect SLA must be preserved (constrains implementation to async)",
    "Q7": "Store hashed IP only (SHA-256) — GDPR-safe",
}


def create_ambiguous_requirement(
    raw_text: str = DEFAULT_REQUIREMENT_TEXT,
) -> Requirement:
    """Build the ambiguous Requirement for the analytics scenario."""
    return Requirement(
        title="Add Analytics to URL Shortener — Ambiguous Requirement",
        raw_text=raw_text,
        requirement_type=RequirementType.AMBIGUOUS,
        ambiguities=[
            AmbiguityItem(field=f, description=d)
            for f, d in [
                ("analytics_metrics", "What data to collect is unspecified"),
                ("access_control", "Who may read analytics is unspecified"),
                ("data_retention", "How long to keep data is unspecified"),
                ("processing_model", "Sync vs async recording is unspecified"),
                ("interface_type", "API vs UI is unspecified"),
                ("redirect_sla", "SLA impact is unspecified"),
                ("privacy_compliance", "IP storage policy is unspecified"),
            ]
        ],
    )


def create_ambiguous_workflow() -> WorkflowDefinition:
    """Build the linear DAG for the ambiguous analytics scenario."""
    return WorkflowDefinition(
        name="ambiguous_analytics",
        description="Ambiguous requirement: 'Add analytics to URL shortener' — detect, clarify, normalise, plan, validate",
        version="1.0.0",
        stages=[
            "ambiguity_detection",
            "clarification",
            "normalization",
            "task_planning",
            "validation",
        ],
        dependencies=[
            StageDependency(from_stage="ambiguity_detection", to_stage="clarification"),
            StageDependency(from_stage="clarification",        to_stage="normalization"),
            StageDependency(from_stage="normalization",        to_stage="task_planning"),
            StageDependency(from_stage="task_planning",        to_stage="validation"),
        ],
    )


def create_ambiguous_stages(
    clarification_gateway: ClarificationGateway | None = None,
) -> dict[str, BaseStage]:
    """Instantiate all stage implementations for the ambiguous scenario."""
    gw = clarification_gateway or PresetClarificationGateway(DEFAULT_PRESET_ANSWERS)
    return {
        "ambiguity_detection": AmbiguityDetectionStage(),
        "clarification":       ClarificationStage(gateway=gw),
        "normalization":       RequirementNormalizationStage(),
        "task_planning":       TaskPlanningStage(),
        "validation":          AmbiguousValidationStage(),
    }


async def run_ambiguous_scenario(
    raw_requirement: str = DEFAULT_REQUIREMENT_TEXT,
    clarification_gateway: ClarificationGateway | None = None,
    approval_gateway: ApprovalGateway | None = None,
    policy_engine: PolicyEngine | None = None,
) -> "WorkflowState":  # type: ignore[name-defined]
    """
    Run the full ambiguous analytics scenario.

    Args:
        raw_requirement:        Raw ambiguous requirement text.
        clarification_gateway:  Gateway for human clarification answers.
                                Defaults to PresetClarificationGateway with
                                DEFAULT_PRESET_ANSWERS.
        approval_gateway:       Gateway for final human approval (validation stage).
                                Defaults to AutoApproveGateway.
        policy_engine:          Optional governance PolicyEngine.

    Returns:
        WorkflowState after the pipeline completes.
    """
    from orchestrator.core.autonomy import AutoApproveGateway

    requirement = create_ambiguous_requirement(raw_requirement)
    definition = create_ambiguous_workflow()
    stages = create_ambiguous_stages(clarification_gateway)

    engine = WorkflowEngine(
        definition=definition,
        stages=stages,
        approval_gateway=approval_gateway or AutoApproveGateway(),
        policy_engine=policy_engine,
    )
    return await engine.run(requirement)
